project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description: "Course Projects for STA 9750 at Baruch College"
  site-url: "https://DolmaDev.github.io/STA9750-2025-FALL/"
  navbar:
    background: primary
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: mp01.qmd
        text: MP01
      - href: mp02.qmd
        text: MP02
      - href: mp03.qmd
        text: MP03
      - href: nightlife_noise_analysis.qmd
        text: Nightlife Noise Analysis
      - href: Group_Project.qmd
        text: Nightlife Analysis
format:
  html:
    theme: sandstone
    toc: false

editor:
  mode: source
